/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NewRouteImport } from './routes/new'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ItinerariesSlugRouteImport } from './routes/itineraries.$slug'
import { Route as MyIndexRouteImport } from './routes/my.index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiUploadsSplatRouteImport } from './routes/api/uploads/$'
import { Route as MyIdEditRouteImport } from './routes/my.$id.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ItinerariesSlugRoute = ItinerariesSlugRouteImport.update({
  id: '/itineraries/$slug',
  path: '/itineraries/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MyIndexRoute = MyIndexRouteImport.update({
  id: '/my/',
  path: '/my/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadsSplatRoute = ApiUploadsSplatRouteImport.update({
  id: '/api/uploads/$',
  path: '/api/uploads/$',
  getParentRoute: () => rootRouteImport,
} as any)
const MyIdEditRoute = MyIdEditRouteImport.update({
  id: '/my/$id/edit',
  path: '/my/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/new': typeof NewRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/itineraries/$slug': typeof ItinerariesSlugRoute
  '/my/': typeof MyIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/uploads/$': typeof ApiUploadsSplatRoute
  '/my/$id/edit': typeof MyIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/new': typeof NewRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/itineraries/$slug': typeof ItinerariesSlugRoute
  '/my': typeof MyIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/uploads/$': typeof ApiUploadsSplatRoute
  '/my/$id/edit': typeof MyIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/new': typeof NewRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/itineraries/$slug': typeof ItinerariesSlugRoute
  '/my/': typeof MyIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/uploads/$': typeof ApiUploadsSplatRoute
  '/my/$id/edit': typeof MyIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/explore'
    | '/forgot-password'
    | '/login'
    | '/new'
    | '/reset-password'
    | '/signup'
    | '/itineraries/$slug'
    | '/my/'
    | '/api/auth/$'
    | '/api/uploads/$'
    | '/my/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/explore'
    | '/forgot-password'
    | '/login'
    | '/new'
    | '/reset-password'
    | '/signup'
    | '/itineraries/$slug'
    | '/my'
    | '/api/auth/$'
    | '/api/uploads/$'
    | '/my/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/explore'
    | '/forgot-password'
    | '/login'
    | '/new'
    | '/reset-password'
    | '/signup'
    | '/itineraries/$slug'
    | '/my/'
    | '/api/auth/$'
    | '/api/uploads/$'
    | '/my/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExploreRoute: typeof ExploreRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  NewRoute: typeof NewRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  ItinerariesSlugRoute: typeof ItinerariesSlugRoute
  MyIndexRoute: typeof MyIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiUploadsSplatRoute: typeof ApiUploadsSplatRoute
  MyIdEditRoute: typeof MyIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/itineraries/$slug': {
      id: '/itineraries/$slug'
      path: '/itineraries/$slug'
      fullPath: '/itineraries/$slug'
      preLoaderRoute: typeof ItinerariesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my/': {
      id: '/my/'
      path: '/my'
      fullPath: '/my/'
      preLoaderRoute: typeof MyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/uploads/$': {
      id: '/api/uploads/$'
      path: '/api/uploads/$'
      fullPath: '/api/uploads/$'
      preLoaderRoute: typeof ApiUploadsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my/$id/edit': {
      id: '/my/$id/edit'
      path: '/my/$id/edit'
      fullPath: '/my/$id/edit'
      preLoaderRoute: typeof MyIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExploreRoute: ExploreRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  NewRoute: NewRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  ItinerariesSlugRoute: ItinerariesSlugRoute,
  MyIndexRoute: MyIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiUploadsSplatRoute: ApiUploadsSplatRoute,
  MyIdEditRoute: MyIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
