/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AppExploreRouteImport } from './routes/_app.explore'
import { Route as AppNewRouteImport } from './routes/_app.new'
import { Route as AppItinerariesSlugRouteImport } from './routes/_app.itineraries.$slug'
import { Route as AppMyIndexRouteImport } from './routes/_app.my.index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiUploadsSplatRouteImport } from './routes/api/uploads/$'
import { Route as AppMyIdEditRouteImport } from './routes/_app.my.$id.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AppExploreRoute = AppExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => AppRoute,
} as any)
const AppNewRoute = AppNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppRoute,
} as any)
const AppItinerariesSlugRoute = AppItinerariesSlugRouteImport.update({
  id: '/itineraries/$slug',
  path: '/itineraries/$slug',
  getParentRoute: () => AppRoute,
} as any)
const AppMyIndexRoute = AppMyIndexRouteImport.update({
  id: '/my/',
  path: '/my/',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadsSplatRoute = ApiUploadsSplatRouteImport.update({
  id: '/api/uploads/$',
  path: '/api/uploads/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppMyIdEditRoute = AppMyIdEditRouteImport.update({
  id: '/my/$id/edit',
  path: '/my/$id/edit',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/explore': typeof AppExploreRoute
  '/new': typeof AppNewRoute
  '/itineraries/$slug': typeof AppItinerariesSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/uploads/$': typeof ApiUploadsSplatRoute
  '/my/': typeof AppMyIndexRoute
  '/my/$id/edit': typeof AppMyIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/explore': typeof AppExploreRoute
  '/new': typeof AppNewRoute
  '/itineraries/$slug': typeof AppItinerariesSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/uploads/$': typeof ApiUploadsSplatRoute
  '/my': typeof AppMyIndexRoute
  '/my/$id/edit': typeof AppMyIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_app/explore': typeof AppExploreRoute
  '/_app/new': typeof AppNewRoute
  '/_app/itineraries/$slug': typeof AppItinerariesSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/uploads/$': typeof ApiUploadsSplatRoute
  '/_app/my/': typeof AppMyIndexRoute
  '/_app/my/$id/edit': typeof AppMyIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/explore'
    | '/new'
    | '/itineraries/$slug'
    | '/api/auth/$'
    | '/api/uploads/$'
    | '/my/'
    | '/my/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/explore'
    | '/new'
    | '/itineraries/$slug'
    | '/api/auth/$'
    | '/api/uploads/$'
    | '/my'
    | '/my/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/_app/explore'
    | '/_app/new'
    | '/_app/itineraries/$slug'
    | '/api/auth/$'
    | '/api/uploads/$'
    | '/_app/my/'
    | '/_app/my/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiUploadsSplatRoute: typeof ApiUploadsSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/explore': {
      id: '/_app/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof AppExploreRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/new': {
      id: '/_app/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof AppNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/itineraries/$slug': {
      id: '/_app/itineraries/$slug'
      path: '/itineraries/$slug'
      fullPath: '/itineraries/$slug'
      preLoaderRoute: typeof AppItinerariesSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/my/': {
      id: '/_app/my/'
      path: '/my'
      fullPath: '/my/'
      preLoaderRoute: typeof AppMyIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/uploads/$': {
      id: '/api/uploads/$'
      path: '/api/uploads/$'
      fullPath: '/api/uploads/$'
      preLoaderRoute: typeof ApiUploadsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/my/$id/edit': {
      id: '/_app/my/$id/edit'
      path: '/my/$id/edit'
      fullPath: '/my/$id/edit'
      preLoaderRoute: typeof AppMyIdEditRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppExploreRoute: typeof AppExploreRoute
  AppNewRoute: typeof AppNewRoute
  AppItinerariesSlugRoute: typeof AppItinerariesSlugRoute
  AppMyIndexRoute: typeof AppMyIndexRoute
  AppMyIdEditRoute: typeof AppMyIdEditRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppExploreRoute: AppExploreRoute,
  AppNewRoute: AppNewRoute,
  AppItinerariesSlugRoute: AppItinerariesSlugRoute,
  AppMyIndexRoute: AppMyIndexRoute,
  AppMyIdEditRoute: AppMyIdEditRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiUploadsSplatRoute: ApiUploadsSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
